-- Single-row user profile (id is always 1).
CREATE TABLE IF NOT EXISTS user (
  id         INTEGER PRIMARY KEY,
  first_name TEXT NOT NULL DEFAULT '',
  last_name  TEXT NOT NULL DEFAULT ''
);
-- Seed the single row so reads never return empty.
INSERT OR IGNORE INTO user (id) VALUES (1);

-- Reading entries: one row per book or article the user has logged.
CREATE TABLE IF NOT EXISTS entries (
  id         TEXT PRIMARY KEY,        -- UUID generated by the frontend
  type       TEXT NOT NULL            -- 'book' | 'article'
               CHECK (type IN ('book', 'article')),
  title      TEXT NOT NULL,
  author     TEXT NOT NULL,
  created_at TEXT NOT NULL            -- ISO-8601 timestamp
);

-- Long-form content attached to an entry (1:1 with entries).
-- article_content is NULL for book entries.
CREATE TABLE IF NOT EXISTS entry_content (
  id               TEXT PRIMARY KEY,  -- same UUID as the parent entry
  entry_id         TEXT NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
  analysis         TEXT NOT NULL DEFAULT '',
  article_content  TEXT,
  url              TEXT,              -- source URL; only set for article entries
  updated_at       TEXT NOT NULL      -- ISO-8601 timestamp
);
